/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.panels;
import GUI.panels.MainFrame; 

public class DialoguePanel extends javax.swing.JPanel {

        // CODE HERE
       private MainFrame mainPanel;
       private SettingsPanel settings;
       
    public DialoguePanel() {
        initComponents();
    }

     public DialoguePanel(MainFrame mainPanel) {
           this.mainPanel = mainPanel; 
           settings = new SettingsPanel(mainPanel);
           initComponents();
    }
    
    
     
     
     
     
     
     // BELOW IS THE CODE GENERATURED FROM NETBEANS
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconPP = new javax.swing.JLabel();
        lblcountPP = new javax.swing.JLabel();
        iconLP = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSettings = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDialogue = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(1280, 720));

        iconPP.setText("Performance Points:");

        lblcountPP.setText("00");

        iconLP.setText("Love Points:");

        jLabel4.setText("00");

        btnSettings.setText("settings");
        btnSettings.addActionListener(this::btnSettingsActionPerformed);

        txtDialogue.setEditable(false);
        txtDialogue.setColumns(20);
        txtDialogue.setRows(5);
        txtDialogue.setText("fasdfafaffdasf");
        txtDialogue.setFocusable(false);
        txtDialogue.setHighlighter(null);
        jScrollPane1.setViewportView(txtDialogue);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(iconPP)
                        .addGap(18, 18, 18)
                        .addComponent(lblcountPP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSettings)
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(iconLP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(109, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iconPP)
                    .addComponent(lblcountPP)
                    .addComponent(btnSettings))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(iconLP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 398, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingsActionPerformed

        settings.showAsPopup(); // We'll add this method
    }//GEN-LAST:event_btnSettingsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSettings;
    private javax.swing.JLabel iconLP;
    private javax.swing.JLabel iconPP;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcountPP;
    private javax.swing.JTextArea txtDialogue;
    // End of variables declaration//GEN-END:variables
}
