/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.panels;
import java.awt.EventQueue; 
import java.awt.CardLayout;
import javax.swing.JPanel;
/**
 *
 * @author renmaya
 */
public class MainFrame extends javax.swing.JFrame {
    
    // CODE HERE
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    private CardLayout cardLayout;
    private JPanel mainContainer;
    
   
    public MainFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        panelObjects();

        // Show title screen first
        this.setContentPane(mainContainer);
        cardLayout.show(mainContainer, "title");
    }
    
    public void showScreen(String screenName) {
    cardLayout.show(mainContainer, screenName);
}
    
    public void panelObjects(){
        cardLayout = new CardLayout();
        mainContainer = new JPanel(cardLayout);
        
        TitleScreenPanel titlePanel = new TitleScreenPanel(this); 
        DialoguePanel dialoguePanel = new DialoguePanel(this);
        SettingsPanel settingsPanel = new SettingsPanel(this);    
        
        mainContainer.add(titlePanel, "title");
        mainContainer.add(dialoguePanel, "dialogue");
        mainContainer.add(settingsPanel, "settings");
    }
    
    
    
    // BELOW IS THE CODE GENERATURED FROM NETBEANS
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}

