/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.panels;

import java.awt.CardLayout;
import javax.swing.JPanel;

public class MainFrame extends javax.swing.JFrame {
    
    // CODE HERE
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    private CardLayout cardLayout;
    private JPanel mainContainer;
    
   
    public MainFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        panelObjects();

        // Show title screen first
        this.setContentPane(mainContainer);
        cardLayout.show(mainContainer, "title");
    }
    
    public void showScreen(String screenName) {
        cardLayout.show(mainContainer, screenName);
        
         if (screenName.equals("dialogue")) {
            InteractionPanel dp = (InteractionPanel) mainContainer.getComponent(1); // or however you access it
            dp.loadTestContent();
        }
    }
    
    public void panelObjects(){
        cardLayout = new CardLayout();
        mainContainer = new JPanel(cardLayout);
        
        TitleScreenPanel titlePanel = new TitleScreenPanel(this); 
        InteractionPanel dialoguePanel = new InteractionPanel(this);
        SettingsPanel settingsPanel = new SettingsPanel(this);    
        
//        SavePanel savePanel = new SavePanel(this);
//        ShiftPanel shiftPanel = new shiftPanel(this);
//        InventoryPanel inventoryPanel = new InventoryPanel(this);
//        ShopPanel shopPanel = new ShopPanel(this);
              
        
        mainContainer.add(titlePanel, "title");
        mainContainer.add(dialoguePanel, "dialogue");
        mainContainer.add(settingsPanel, "settings");
        
//        mainContainer.add(shiftPanel, "shift");
//        mainContainer.add(shopPanel, "shop");
//        mainContainer.add(inventoryPanel, "inventory");
//        mainContainer.add(savePanel, "save");
        
    }
    
    
    
    // BELOW IS THE CODE GENERATURED FROM NETBEANS
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}

