/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.panels;

import java.awt.CardLayout;
import javax.swing.JPanel;

public class MainFrame extends javax.swing.JFrame {
    
    private CardLayout cardLayout;
    private JPanel mainContainer;
    
    private TitleScreenPanel titlePanel;
    private InteractionPanel dialoguePanel;
    private SettingsPanel settingsPanel; // This is for popup ONLY - NOT added to CardLayout
    private ShiftPanel shiftPanel;
    
    private String currentScreen = "title";
    
    public MainFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        panelObjects();
        this.setContentPane(mainContainer);
        cardLayout.show(mainContainer, "title");
    }
    
    public void showScreen(String screenName) {
        currentScreen = screenName;
        cardLayout.show(mainContainer, screenName);
        
        if (screenName.equals("dialogue") && dialoguePanel != null) {
            dialoguePanel.loadTestContent();
        }
        if (screenName.equals("shift") && shiftPanel != null) {
            shiftPanel.loadTestCall();
        }
    }
    
    public void panelObjects(){
        cardLayout = new CardLayout();
        mainContainer = new JPanel(cardLayout);
        
        titlePanel = new TitleScreenPanel(this);
        
        // Create ONE SettingsPanel instance to be shared for popups
        // This is NOT added to the CardLayout container
        settingsPanel = new SettingsPanel(this);
        
        // Pass the SAME settingsPanel instance to both panels
        dialoguePanel = new InteractionPanel(this, settingsPanel);
        shiftPanel = new ShiftPanel(this, settingsPanel);
        
        mainContainer.add(titlePanel, "title");
        mainContainer.add(dialoguePanel, "dialogue");
        // DO NOT ADD settingsPanel to the CardLayout - it's only for popups!
        // mainContainer.add(settingsPanel, "settings"); // REMOVE THIS LINE
        mainContainer.add(shiftPanel, "shift");
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    // BELOW IS THE CODE GENERATURED FROM NETBEANS
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}

