/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.panels;

import GUI.panels.MainFrame;
import javax.swing.*;
import java.awt.*;

public class SettingsPanel extends javax.swing.JPanel {
    
    private MainFrame mainFrame;
    private JDialog dialog;
    
    public SettingsPanel(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
        
        // Style
        setBackground(new Color(50, 50, 50, 240));
        setBorder(BorderFactory.createLineBorder(Color.WHITE, 2));
    }
    
    public void showAsPopup() {
        if (dialog == null) {
            dialog = new JDialog(mainFrame, "Settings", Dialog.ModalityType.APPLICATION_MODAL);
            dialog.setUndecorated(true);
            dialog.setSize(300, 350);
            dialog.setContentPane(this);
        }
        
        // ✅ FORCE center on mainFrame EVERY time
        dialog.setLocationRelativeTo(mainFrame);
        
        // Make sure dialog is on top
        dialog.setAlwaysOnTop(true);
        
        dialog.setVisible(true);
    }
    
    public void hidePopup() {
        if (dialog != null && dialog.isVisible()) {
            dialog.dispose();
        }
    }
    

    
    // Add getters for buttons if needed
    public javax.swing.JButton getBtnContinue() { return btnContinue; }
    public javax.swing.JButton getBtnExit() { return btnExit; }
    public javax.swing.JButton getBtnSaves() { return btnSaves; }
    
    
    
    // NETBEANS CODE AND EVENT HANDLERS

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExit = new javax.swing.JButton();
        btnSaves = new javax.swing.JButton();
        btnContinue = new javax.swing.JButton();
        lblSettings = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(300, 350));

        btnExit.setText("Exit");
        btnExit.addActionListener(this::btnExitActionPerformed);

        btnSaves.setText("Saves");
        btnSaves.addActionListener(this::btnSavesActionPerformed);

        btnContinue.setText("Continue");
        btnContinue.addActionListener(this::btnContinueActionPerformed);

        lblSettings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSettings.setText("SETTINGS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnContinue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSaves, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(lblSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnContinue)
                .addGap(18, 18, 18)
                .addComponent(btnSaves)
                .addGap(18, 18, 18)
                .addComponent(btnExit)
                .addContainerGap(61, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        if (mainFrame != null) {
            mainFrame.showScreen("title"); // Go to title screen
            hidePopup();
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavesActionPerformed
        JOptionPane.showMessageDialog(this, "Game Saved!");  
    }//GEN-LAST:event_btnSavesActionPerformed

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed
                hidePopup(); 
    }//GEN-LAST:event_btnContinueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinue;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSaves;
    private javax.swing.JLabel lblSettings;
    // End of variables declaration//GEN-END:variables
}
