package GUI.panels;

import GUI.panels.MainFrame;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class SettingsPanel extends javax.swing.JPanel {
    
    private MainFrame mainFrame;
    private JDialog dialog;
    private String previousScreen = "shift";
    private WindowListener currentListener;
    private boolean isHiding = false; // Flag to prevent recursive hiding/showing
    
    public SettingsPanel(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
    }
    
    public void setPreviousScreen(String screen) {
        this.previousScreen = screen;
    }
    
    public void showAsPopup(WindowListener listener) {
        // Don't show if we're in the process of hiding
        if (isHiding) {
            return;
        }
        
        // Store the listener
        this.currentListener = listener;
        
        // Always create a new dialog to avoid reuse issues
        if (dialog != null && dialog.isVisible()) {
            dialog.dispose();
        }
        
        // Create new dialog
        dialog = new JDialog(mainFrame, "Settings", Dialog.ModalityType.APPLICATION_MODAL);
        dialog.setUndecorated(true);
        dialog.setSize(300, 350);
        dialog.setContentPane(this);
        
        // Add the provided window listener
        if (listener != null) {
            dialog.addWindowListener(listener);
        }
        
        // Add key listener for ESC key
        dialog.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ESCAPE) {
                    hidePopup();
                }
            }
        });
        
        dialog.setFocusable(true);
        dialog.setLocationRelativeTo(mainFrame);
        dialog.setAlwaysOnTop(true);
        
        // Add a window focus listener to detect when dialog is closing
        dialog.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                // Reset the hiding flag when dialog is fully closed
                isHiding = false;
            }
        });
        
        dialog.setVisible(true);
    }
    
    public void hidePopup() {
        if (dialog != null && dialog.isVisible()) {
            // Remove the window listener to prevent multiple triggers
            if (currentListener != null) {
                dialog.removeWindowListener(currentListener);
            }
            dialog.dispose();
            dialog = null;
        }
     }
    
    public void showAsPopup() {
        showAsPopup(null);
    }
    
    
    
    
    
    
    
    
    
    // NETBEANS CODE AND EVENT HANDLERS

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExit = new javax.swing.JButton();
        btnSaves = new javax.swing.JButton();
        btnContinue = new javax.swing.JButton();
        lblSettings = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(300, 350));

        btnExit.setText("Exit");
        btnExit.setFocusable(false);
        btnExit.addActionListener(this::btnExitActionPerformed);

        btnSaves.setText("Saves");
        btnSaves.setFocusable(false);
        btnSaves.addActionListener(this::btnSavesActionPerformed);

        btnContinue.setText("Continue");
        btnContinue.setFocusable(false);
        btnContinue.addActionListener(this::btnContinueActionPerformed);

        lblSettings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSettings.setText("SETTINGS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnContinue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSaves, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(lblSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnContinue)
                .addGap(18, 18, 18)
                .addComponent(btnSaves)
                .addGap(18, 18, 18)
                .addComponent(btnExit)
                .addContainerGap(61, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        if (mainFrame != null) {
            mainFrame.showScreen("title"); 
            hidePopup();
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavesActionPerformed
        JOptionPane.showMessageDialog(this, "Game Saved!");  
    }//GEN-LAST:event_btnSavesActionPerformed

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed
                hidePopup(); 
    }//GEN-LAST:event_btnContinueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinue;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSaves;
    private javax.swing.JLabel lblSettings;
    // End of variables declaration//GEN-END:variables
}
