package GUI.panels;

import GUI.panels.universalComponents.BackgroundLayer;
import GUI.panels.universalComponents.TopBarComponents;
import GUI.panels.shopComponents.ShopLayer;
import GUI.panels.inventoryComponents.ItemLayer;
import Entities.Item;
import Entities.ActiveEffects;
import java.awt.Dimension;
import javax.swing.JPanel;
import javax.swing.OverlayLayout;

public class ShopPanel extends JPanel {

    private final MainFrame     mainPanel;
    private final SettingsPanel settings;

    private BackgroundLayer  bg;
    private TopBarComponents topBar;
    private ShopLayer        shopBox;
    private InventoryPanel   inventory;

    public ShopPanel(MainFrame mainPanel, SettingsPanel sharedSettings) {
        this.mainPanel = mainPanel;
        this.settings  = sharedSettings;
        setPreferredSize(new Dimension(1280, 720));
        setLayout(new OverlayLayout(this));
        initializeLayers();
    }

    public void loadShop() {
        topBar.updateForShop(mainPanel.getCurrentDay());
        topBar.setPpValue(mainPanel.getPP());
        topBar.setLpValue(mainPanel.getLP());
        topBar.setSalaryValue(mainPanel.getSalary());

        shopBox.load(); // ensures initItems() has run before we share the list
        inventory.setItems(shopBox.getShopItems());
        shopBox.setPlayerFunds(mainPanel.getSalary());

        shopBox.setOnPurchase((item, cost) -> {
            mainPanel.setSalary(mainPanel.getSalary() - cost);
            topBar.setSalaryValue(mainPanel.getSalary());
            inventory.setItems(shopBox.getShopItems());
        });

        shopBox.setOnExit(() -> {
            saveStats();
            mainPanel.onShopComplete();
        });
    }

    private void saveStats() {
        mainPanel.setPP(topBar.getCurrentPpValue());
        mainPanel.setSalary(topBar.getCurrentSalaryValue());
    }

    private void initializeLayers() {
        bg = new BackgroundLayer();
        bg.setBackgroundFromFile("ConvenienceStore.jpg");

        topBar = new TopBarComponents(mainPanel);
        topBar.setSettingsPanel(settings);
        topBar.setParentScreen("shop");

        inventory = new InventoryPanel(mainPanel);
        topBar.setInventoryPanel(inventory);

        inventory.setOnItemEffect((effectType, effectValue) -> {
            ActiveEffects fx = mainPanel.getActiveEffects();
            if (effectType == Item.EffectType.LP_FLAT) {
                String activeChar = mainPanel.getRouteManager().hasActiveRoute()
                    ? mainPanel.getRouteManager().getActiveCharacter() : null;
                if (activeChar != null) {
                    mainPanel.getRouteManager().addCharacterLP(activeChar, effectValue);
                    topBar.addLpPoints(effectValue);
                }
            } else {
                fx.apply(effectType, effectValue);
            }
        });

        shopBox = new ShopLayer();

        add(topBar);
        add(shopBox);
        add(bg);
    }

    @Override public Dimension getMinimumSize()   { return new Dimension(1280, 720); }
    @Override public Dimension getMaximumSize()   { return new Dimension(1280, 720); }
    @Override public Dimension getPreferredSize() { return new Dimension(1280, 720); }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new javax.swing.OverlayLayout(this));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
